#!/bin/sh
# $XConsortium: xinitrc.cpp,v 1.4 91/08/22 11:41:34 rws Exp $

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/usr/X11R6/lib/X11/xinit/.Xresources
sysmodmap=/usr/X11R6/lib/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f $userresources ]; then
    xrdb -merge $userresources
fi

if [ -f $usermodmap ]; then
    xmodmap $usermodmap
fi

numlockx &
eval `cat $HOME/.fehbg` &

# Ask for keychain password
keychain --clear -q ~/.ssh/miker
source ~/.keychain/`hostname`-sh > /dev/null

# Start the window manager:
exec /usr/X11R6/bin/startfluxbox
#xsetroot -solid black &
#exec /usr/bin/openbox-session
#exec /usr/bin/fvwm-crystal
