#!/bin/bash

REPO="${1}"

CONF_FILE="/etc/paludis/repositories/${REPO}.conf"
DISABLED_FILE="/etc/paludis/repositories/${REPO}.conf.disabled"


if [[ $UID -ne 0 ]]; then
    echo "Must be root"
    exit 1
fi

if [[ -z ${REPO} ]]; then
    echo "Enable a single repository:"
    echo "eg. ${0} mozilla"
    exit 1
fi

if [[ -f ${DISABLED_FILE} ]]; then
    echo "Enabling ${REPO}"
    mv ${DISABLED_FILE} ${CONF_FILE}

    echo "${CONF_FILE} Enabled"
    exit 0
else
    echo "${DISABLED_FILE} could not be found"
    exit 1
fi
