#!/usr/bin/env ruby
# Distributed under the terms of the GNU General Public License v2
# Copyright (c) 2009 Greg Fitzgerald <netzdamon@gmail.com>
# vim: set sw=2 sts=2 et tw=80 :
# Should open the following types
# archives, images, http/https, gopher, ftp/ftps, ssh, documents
# need to use some type of mimetype to keep this sane, this is just a working
# example currenty.
args = ARGV.clone
@IMG_EXTENSIONS = [ "jpg", "jpeg", "tiff", "gif", "png", "bmp"] 

args.each do |arg|
  case args
  when /.(txt|text)/i
    system %Q{vim #{arg}}
  when /(http|https):\/\/\w.?\w.\w{2,3}/i
    system %Q{firefox -new-tab #{arg}}
  when /(ftp|ftps):\/\/\w.?\w.\w{2,3}/i
    system %Q{lftp #{arg}}
  else
    if File.file?("#{arg}")
      @IMG_EXTENSIONS.each do |ext|
        if File.extname("#{arg}") =~ /\.#{ext}$/i
          system %Q{feh -w #{arg}}
        end
      end
    end
  end
end
