#!/bin/sh

BUNDLEDIR="/home/gregf/.vim/bundle/"

if [[ -d ${BUNDLEDIR} ]]; then
    cd ${BUNDLEDIR}
else
    echo "${BUNDLEDIR} does not exist!"
    exit 1
fi

for plugin in *; do
    cd ${plugin}
    if [[ -d ${PWD}/.git ]]; then
        git pull
    elif [[ -d ${PWD}/.svn ]]; then
        svn update
    elif [[ -d ${PWD}/.hg ]]; then
        hg update
    else
        echo "No Source Control Found"
    fi
    echo "Updated: ${plugin}"
    cd ${BUNDLEDIR}
done
