#! /bin/zsh

if [ x"$HOME" = x ] ; then
        export HOME=$(cd ~ ; pwd)
fi

if [ x"$HOSTNAME" = x ] ; then
        export HOSTNAME=$(hostname)
fi

export EMAIL="bart@jukie.net"
export FULLNAME="Bart Trojanowski"

#export DEBEMAIL=$EMAIL
#export DEBFULLNAME=$FULLNAME

#export GIT_AUTHOR_NAME=$FULLNAME
#export GIT_COMMITTER_NAME=$FULLNAME
#export GIT_AUTHOR_EMAIL=$EMAIL
#export GIT_COMMITTER_EMAIL=$EMAIL

export IRCNICK=bartman
export IRCNAME=${FULLNAME}
export IRCSERVER=irc.irc.irc
export IRC_SERVERS_FILE="$HOME/.irc-serv"

export CVS_RSH="ssh"
export CVSREAD=yes
export MANWIDTH=80
export EDITOR=vim
export VISUAL=vim
#export CCACHE_DIR=$HOME/.ccache

export INPUTRC="~/.inputrc"
export MAIL="${HOME}/mail/inbox"

export RLWRAP_HOME=~/.cache/rlwrap/
export GTK_IM_MODULE=xim

export LC_MESSAGES=C
export LC_ALL=

if [ $UID -eq 0 ]; then
        PATH=~root/bin:$PATH
elif ( ${HOME}/usr/bin/git version >/dev/null 2>/dev/null ) ; then

        #echo "using git from ~/usr/bin/ - " $( ${HOME}/usr/bin/git version )

        export PATH="${HOME}/bin:${PATH}"
        export PATH="${HOME}/usr/bin:${PATH}"
        export MANPATH="${HOME}/usr/share/man/:${MANPATH}"

        export GIT_EXEC_PATH="${HOME}/usr/bin"
        #export GITPERLLIB=$(ls -1d ${HOME}/usr/lib/perl/*/|head -n1)

else
        PATH="${HOME}/bin:${PATH}"
fi

PATH="$PATH:/bin:/usr/bin:/usr/local/bin"
PATH="$PATH:/sbin:/usr/sbin:/usr/local/sbin"
PATH="$PATH:/usr/X11R6/bin"
export PATH

# this makes man pages look nicer...
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

# these are the default arguments to exuberant-ctags
CTAGS="--c++-kinds=+p --fields=+iaS --extra=+q"
