#!/bin/bash 
# Modified by Keld Simonsen keld@dkuug.dk 2004-10-08

# The Ultimate Setup For Your Internet Connection At Home.
# Similar to wondershaper
# Does not delay LAN traffic.
# 
#
# Set the following values to somewhat less (maybe 20 %)s
# than your actual download and uplink speed. In kilobits
DOWNLINK=210
UPLINK=210
DEV=eth0
LAN=192.168.0.0/16
LANSPEED=100mbit

# clean existing down- and uplink qdiscs, hide errors
tc qdisc del dev $DEV root    2> /dev/null > /dev/null
tc qdisc del dev $DEV ingress 2> /dev/null > /dev/null

###### uplink

# install root CBQ

tc qdisc add dev $DEV root handle 1: cbq avpkt 1000 bandwidth 100mbit 

# shape external traffic at $UPLINK speed - this prevents huge queues in your
# DSL modem which destroy latency:
# main class

tc class add dev $DEV parent 1: classid 1:1 cbq rate ${UPLINK}kbit \
allot 1500 prio 5 bounded isolated 

# LAN prio class 1:10:

tc class add dev $DEV parent 1: classid 1:10 cbq rate $LANSPEED \
   allot 1600 prio 1 bounded isolated

# high prio class 1:20:

tc class add dev $DEV parent 1:1 classid 1:20 cbq rate ${UPLINK}kbit \
   allot 1600 prio 1 avpkt 1000

# bulk and default class 1:30 - gets slightly less traffic, 
#  and a lower priority:

tc class add dev $DEV parent 1:1 classid 1:30 cbq rate $[9*$UPLINK/10]kbit \
   allot 1600 prio 2 avpkt 1000

# all get Stochastic Fairness:
tc qdisc add dev $DEV parent 1:10 handle 10: sfq perturb 10
tc qdisc add dev $DEV parent 1:20 handle 20: sfq perturb 10
tc qdisc add dev $DEV parent 1:30 handle 30: sfq perturb 10

# start filters

# LAN filter
tc filter add dev $DEV parent 1: protocol ip prio 10 u32 \
      match ip dst $LAN flowid 1:10

# TOS Minimum Delay (ssh, NOT scp) in 1:20:
tc filter add dev $DEV parent 1:0 protocol ip prio 10 u32 \
      match ip tos 0x10 0xff  flowid 1:20

# ICMP (ip protocol 1) in the interactive class 1:20 so we 
# can do measurements and impress our friends:
tc filter add dev $DEV parent 1:0 protocol ip prio 11 u32 \
	match ip protocol 1 0xff flowid 1:20

# To speed up downloads while an upload is going on, put ACK packets in
# the interactive class:

tc filter add dev $DEV parent 1: protocol ip prio 12 u32 \
   match ip protocol 6 0xff \
   match u8 0x05 0x0f at 0 \
   match u16 0x0000 0xffc0 at 2 \
   match u8 0x10 0xff at 33 \
   flowid 1:20

# rest is 'non-interactive' ie 'bulk' and ends up in 1:20

tc filter add dev $DEV parent 1: protocol ip prio 13 u32 \
   match ip dst 0.0.0.0/0 flowid 1:30

########## downlink #############
# slow downloads down to somewhat less than the real speed  to prevent 
# queuing at our ISP. Tune to see how high you can set it.
# ISPs tend to have *huge* queues to make sure big downloads are fast
#
# attach ingress policer:

tc qdisc add dev $DEV handle ffff: ingress

# filter LAN packets without really delaying anything

tc filter add dev $DEV parent ffff: protocol ip prio 50 u32 match ip src \
   $LAN police rate $LANSPEED burst 10m drop flowid :1

# filter external IP (0.0.0.0/0), drop everything that's
# coming in too fast:

tc filter add dev $DEV parent ffff: protocol ip prio 50 u32 match ip src \
   0.0.0.0/0 police rate ${DOWNLINK}kbit burst 10k drop flowid :1

